services:
  pilzno-synagogue-db:
    image: postgres:15-alpine
    container_name: pilzno-synagogue-db
    environment:
      POSTGRES_DB: pilzno_synagogue
      POSTGRES_USER: synagogue_admin
      POSTGRES_PASSWORD: synagogue_secure_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5433:5432"
    volumes:
      - pilzno-synagogue-db-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - pilzno-synagogue-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synagogue_admin -d pilzno_synagogue"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    profiles:
      - dev
      - prod

  pilzno-synagogue-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development  # Override to 'production' for prod builds
    container_name: pilzno-synagogue-backend
    environment:
      DATABASE_URL: postgresql://synagogue_admin:synagogue_secure_pass@pilzno-synagogue-db:5432/pilzno_synagogue
      JWT_SECRET: pilzno_synagogue_jwt_secret_key_2024
      NODE_ENV: development
      DB_HOST: pilzno-synagogue-db
      DB_PORT: 5432
      DB_USER: synagogue_admin
      DB_PASSWORD: synagogue_secure_pass
      DB_NAME: pilzno_synagogue
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      pilzno-synagogue-db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_logs:/app/logs
    networks:
      - pilzno-synagogue-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    profiles:
      - dev
      - prod

  pilzno-synagogue-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development  # Override to 'production' for prod builds
    container_name: pilzno-synagogue-frontend
    environment:
      VITE_API_BASE_URL: http://localhost:3001
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      pilzno-synagogue-backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    networks:
      - pilzno-synagogue-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    profiles:
      - dev
      - prod

volumes:
  pilzno-synagogue-db-data:
    driver: local
  backend_logs:
    driver: local

networks:
  pilzno-synagogue-network:
    driver: bridge 