version: '3.8'

services:
  pilzno-synagogue-db:
    image: postgres:15-alpine
    container_name: pilzno-synagogue-db-external
    environment:
      POSTGRES_DB: pilzno_synagogue
      POSTGRES_USER: synagogue_admin
      POSTGRES_PASSWORD: synagogue_secure_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "0.0.0.0:5433:5432"  # Bind to all interfaces
    volumes:
      - pilzno-synagogue-db-external-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - pilzno-synagogue-external-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synagogue_admin -d pilzno_synagogue"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  pilzno-synagogue-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: pilzno-synagogue-backend-external
    environment:
      DATABASE_URL: postgresql://synagogue_admin:synagogue_secure_pass@pilzno-synagogue-db:5432/pilzno_synagogue
      JWT_SECRET: pilzno_synagogue_jwt_secret_key_2024
      NODE_ENV: development
      DB_HOST: pilzno-synagogue-db
      DB_PORT: 5432
      DB_USER: synagogue_admin
      DB_PASSWORD: synagogue_secure_pass
      DB_NAME: pilzno_synagogue
      PORT: 3001
      # Allow external access
      CORS_ORIGIN: "*"
    ports:
      - "0.0.0.0:3001:3001"  # Bind to all interfaces
    depends_on:
      pilzno-synagogue-db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_logs_external:/app/logs
    networks:
      - pilzno-synagogue-external-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  pilzno-synagogue-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: pilzno-synagogue-frontend-external
    environment:
      # Use external IP for API calls
      VITE_API_BASE_URL: http://89.138.168.239:3001
      NODE_ENV: development
    ports:
      - "0.0.0.0:3000:3000"  # Bind to all interfaces
    depends_on:
      pilzno-synagogue-backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    networks:
      - pilzno-synagogue-external-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  pilzno-synagogue-db-external-data:
    driver: local
  backend_logs_external:
    driver: local

networks:
  pilzno-synagogue-external-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
