# Docker Compose override for HTTPS support
# This file adds HTTPS capabilities to the existing nginx container

version: '3.8'

services:
  nginx-proxy-simple:
    # Extend the existing nginx service
    extends:
      file: docker-compose.yml
      service: nginx-proxy-simple
    ports:
      - "80:80"    # HTTP (redirects to HTTPS)
      - "443:443"  # HTTPS (main entry point)
    volumes:
      - ./nginx/https.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    profiles:
      - https
      - prod
